name: CI_NEXTJS_SOSMED_DOWNLOADER

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: production-artifacts
          path: .next

      - name: Rsync Deployments Action
        # You may pin to the exact commit or the version.
        # uses: Burnett01/rsync-deployments@796cf0d5e4b535745ce49d7429f77cf39e25ef39
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          remote_path: /home/msaepul07150/deployments
          remote_host: msaepul07.gnu.my.id
          remote_port: 11500
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          remote_key_pass: ${{ secrets.SSH_PASS }}
