name: CD Nodejs

on: 
  push: 
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: msaepul07.gnu.my.id
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASS }}
            port: ${{ secrets.SSH_PORT }}
            key: ${{ secrets.DEPLOY_KEY }}
            script: |
              cd ~/deployment
              git pull origin main
              git status
              npm i
              
